name: Generate Documentation

on:
  push:
    paths:
      - 'src/components/**'
      - 'stories/**'
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Generate documentation
        run: |
          node scripts/generate-docs.js
          echo "## Documentation Generated" >> $GITHUB_STEP_SUMMARY
          echo "Components documented: $(ls -1 docs/components/*.md 2>/dev/null | wc -l)" >> $GITHUB_STEP_SUMMARY
      
      - name: Check for changes
        id: check_changes
        run: |
          if [[ -n $(git status --porcelain docs/) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit documentation updates
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/
          git commit -m "docs: auto-generate component documentation [skip ci]"
      
      - name: Push changes
        if: steps.check_changes.outputs.changes == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      
      - name: Create PR comment
        if: github.event_name == 'pull_request' && steps.check_changes.outputs.changes == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '📚 Documentation has been automatically updated for the modified components.'
            })

  update-storybook:
    needs: generate-docs
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build Storybook with docs
        run: |
          npm run build-storybook
          
          # Copy documentation to Storybook static
          mkdir -p storybook-static/docs
          cp -r docs/* storybook-static/docs/ || true
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./storybook-static
      
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
